### ISSUE TITLE
Consistency between API and Organization catalogs

### ISSUE THREAD

**Issue by brylie** [Digipalvelutehdas/APIKA#115]
Currently, the Organization and API catalogs are distinct in several ways:
- The API catalog has different pagination implementation than the Organization catalog
- The Organization and API catalogs have different sort/filter functionality
- The Organization and API catalogs do not use URL parameters for sorting/filtering

# Task
Unify the functionality and style of the Organization and API catalog as much as possible. Make sure to share code and styles as much as possible.

# Definition of done
- [x] APIs catalog has pagination feature
- [x] Both APIs and Organizations catalogs support sorting and filtering
  - [x] Sorting and filtering parameters are stored as URL variables

**Comment by marla-singer** [comment]
@brylie Implemented pagination on APIs catalog and sorting. Now I am working on filtering

**Comment by bajiat** [comment]
@marla-singer Do you want this issue to be split into two different issues?

**Comment by marla-singer** [comment]
@bajiat Yes,please. I'd like to separate redesing of catalog card to different issue

**Comment by brylie** [comment]
@marla-singer I am revising the issue now.

**Comment by brylie** [comment]
Created issue #118 as a follow-up task.

**Comment by Nazarah** [comment]
@marla-singer @brylie : Have you decided on what categories you will consider for both the sorting and filtering option?

**Comment by brylie** [comment]
Here are some:

Sort:
- alphabetical
- date created
- popularity

Filter:
- My APIs
- My Organization(s)

The query parameters don't need to be exact between Organizations and APIs, but should overlap somewhat.

**Comment by Nazarah** [comment]
@brylie : for the organization I suggest to exclude the sort category "popularity". From the weekly update meetings @kyyberi  suggested that we don't need to include popularity/rating options for organizations.

One more suggestion is that we can include "My APIs in Organizations". This would filter the organizations to which an API owner has his/her APIs connected.
