### ISSUE TITLE
Use Bootstrap classes for catalogue templates, extend/override if needed

### ISSUE THREAD

**Issue by brylie** [Digipalvelutehdas/APIKA#118]
# Context
Our API catalog card view is designed with custom markup/classes. While the resulting design is similar to Bootstrap panels, we have to maintain the custom markup ourselves. This means more work when trying to provide a unified design, e.g. between the API and Organizations catalog.

# Task
Use Bootstrap panels to provide most or all of the style rules for API and Organization cards. Add custom CSS only if absolutely needed.

# Rationale
> Code is not an asset, it's a liability
> - [LegacyCode](http://wiki.c2.com/?LegacyCode)
>
> Code is expensive to test and maintain, so if the same work can be done with less code that is a plus.
> - [Software as a Liability](http://wiki.c2.com/?SoftwareAsLiability)
>
> Some code is an asset, just as some land and some cows are assets. Code with low value density or negative net value is a liability
> - [LegacyCode](http://wiki.c2.com/?LegacyCode)

Each time we rely on existing libraries within our project, we increase the value the libraries provide.

We are not planning to migrate away from Bootstrap in the near future, so investing further in Bootstrap seems to be in our interest here.

# Definition of done
- [ ] API and Organization catalogs, cards, and tables use Bootstrap classes
  - [ ] Very little custom CSS remains for each module (e.g. <= 5-10 loc)
  - [ ] Organization and API components share most of their CSS rules

**Comment by Nazarah** [comment]
Related to this task, i earlier made an usability issue about scrambled information in API cards. I am closing #94 as further works would be done in this task. Adding the description of the usability issue in this comment.
> Right now, if an API is made private, then a label appears in the card view.
This pushes the description field lower, which in turn gets scrambled with Bookmark, Starrating and add date information.
We need labels to show visibility of the API as well as its lifecycle phase (future implementation)
[open questionL Also from organization view, we might need to incorporate card actions]
So suggesting to increase height of the card view, so that information are not scrambled with each other

https://cloud.githubusercontent.com/assets/17976243/20885384/340edb72-baf9-11e6-8b69-d8281c5679c7.png

**Comment by bajiat** [comment]
@manzapanza Assigning the task to you. Please ensure the changes fix also the scrambled information in API cards (#94).

**Comment by bajiat** [comment]
Closing as resolved. See PR #228
